### ISSUE TITLE
log-monitor用到的sls和云监控配置是否有支持api

### ISSUE THREAD

**Issue by fengkar** [chemao/log-monitor#3]
减少配置数据，尽量合并三个地方的配置到一个地方。

**Comment by fengkar** [comment]
sls和云监控目前只有数据读写的api, 都没有对日志和监控想定义的api。由于这个修改不是频繁，暂时采用页面配置

**Comment by wsky** [comment]
好吧 回头把操作流程以及每个步骤的意义写一下，最好是来个简易的集成机制图~
